### ISSUE TITLE
The design library running error

### ISSUE THREAD

**Issue by LuShuYangMing** [fengzhanglab/Screening_Protocols_manuscript#6]
Hi
     
I have used the design_library.py run as the following command with twice try:

`python design_library.py  -o output.csv -i Homo_sapiens.GRCh38 -g genes.csv -gecko`
      but always get follow error:
`time used: 257515 seconds`
`PROCESSING IN PARALLEL!!!`
`PROCESSING IN PARALLEL!!!`
`PROCESSING IN PARALLEL!!!`
`PROCESSING IN PARALLEL!!!`
`Traceback (most recent call last):`
  `File "design_library.py", line 503, in <module>`
    `__main__()`
  `File "design_library.py", line 497, in __main__`
    `find_offtargets(args.input_prefix)`
`  File "design_library.py", line 241, in find_offtargets`
   ` with open(tf.name) as f_out:`
`IOError: [Errno 2] No such file or directory: '/tmp/temp.n6aPgN.4.seqmap.output'`

The genes.csv is like this format:
`name,chrom,start,end`
`gene1,num,num,num`
`gene2,num,num,num`

Thank you so much for providing any suggestions.

lushuyangming.

**Comment by mpandela** [comment]
did you ever solve this error? I have the same challenge.
