### ISSUE TITLE
count_spacer.py : ValueError: Sequence and quality captions differ

### ISSUE THREAD

**Issue by geng-lee** [fengzhanglab/Screening_Protocols_manuscript#7]
Hi,

I recently wanted to use your count_spacer.py script but ran into and issue:

` python count_spacers.py  -i lib.csv -f result/merge/lib.fq.gz -no-g -o result/count_spacers/`

> Traceback (most recent call last):
  File "count_spacers.py", line 115, in <module>
    count_spacers(args.input_file, args.fastq_file, args.output_file, args.guide_g)
  File "count_spacers.py", line 49, in count_spacers
    for record in readiter: #contains the seq and Qscore etc.
  File "/backup/home/changxing/anaconda3/envs/CRISPR/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 611, in parse
    for r in i:
  File "/backup/home/changxing/anaconda3/envs/CRISPR/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/backup/home/changxing/anaconda3/envs/CRISPR/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 923, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.`

Best Wishes

**Comment by geng-lee** [comment]
What does library_sequences.csv file content look like, and can you provide a sample file.

**Comment by wangjianparis** [comment]
> What does library_sequences.csv file content look like, and can you provide a sample file.
Biopython works in py3. Transform this script into py3 and put capitalized guide seq in col1
